<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\City;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        City::insert([
            //서울특별시
            ['state_id' => 1, 'city_name' => '종로구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 1, 'city_name' => '중구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 1, 'city_name' => '용산구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 1, 'city_name' => '성동구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 1, 'city_name' => '광진구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 1, 'city_name' => '동대문구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 1, 'city_name' => '중랑구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 1, 'city_name' => '성북구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 1, 'city_name' => '강북구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 1, 'city_name' => '도봉구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 1, 'city_name' => '노원구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 1, 'city_name' => '은평구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 1, 'city_name' => '서대문구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 1, 'city_name' => '마포구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 1, 'city_name' => '양천구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 1, 'city_name' => '강서구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 1, 'city_name' => '구로구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 1, 'city_name' => '금천구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 1, 'city_name' => '영등포구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 1, 'city_name' => '동작구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 1, 'city_name' => '관악구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 1, 'city_name' => '서초구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 1, 'city_name' => '강남구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 1, 'city_name' => '송파구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 1, 'city_name' => '강동구', 'created_at' => now(), 'updated_at' => now(),],
            //부산광역시
            ['state_id' => 2, 'city_name' => '중구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 2, 'city_name' => '서구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 2, 'city_name' => '동구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 2, 'city_name' => '영도구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 2, 'city_name' => '부산진구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 2, 'city_name' => '동래구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 2, 'city_name' => '남구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 2, 'city_name' => '북구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 2, 'city_name' => '해운대구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 2, 'city_name' => '사하구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 2, 'city_name' => '금정구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 2, 'city_name' => '강서구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 2, 'city_name' => '연제구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 2, 'city_name' => '수영구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 2, 'city_name' => '사상구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 2, 'city_name' => '기장구', 'created_at' => now(), 'updated_at' => now(),],
            //대구광역시
            ['state_id' => 3, 'city_name' => '중구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 3, 'city_name' => '동구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 3, 'city_name' => '서구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 3, 'city_name' => '남구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 3, 'city_name' => '북구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 3, 'city_name' => '수성구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 3, 'city_name' => '달서구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 3, 'city_name' => '달성군', 'created_at' => now(), 'updated_at' => now(),],
            //인천광역시
            ['state_id' => 4, 'city_name' => '중구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 4, 'city_name' => '동구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 4, 'city_name' => '미추홀구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 4, 'city_name' => '연수구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 4, 'city_name' => '남동구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 4, 'city_name' => '부평구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 4, 'city_name' => '계양구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 4, 'city_name' => '서구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 4, 'city_name' => '강화군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 4, 'city_name' => '옹진군', 'created_at' => now(), 'updated_at' => now(),],
            //광주광역시
            ['state_id' => 5, 'city_name' => '동구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 5, 'city_name' => '서구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 5, 'city_name' => '남구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 5, 'city_name' => '북구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 5, 'city_name' => '광산구', 'created_at' => now(), 'updated_at' => now(),],
            //대전광역시
            ['state_id' => 6, 'city_name' => '동구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 6, 'city_name' => '중구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 6, 'city_name' => '서구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 6, 'city_name' => '유성구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 6, 'city_name' => '대덕구', 'created_at' => now(), 'updated_at' => now(),],
            //울산광역시
            ['state_id' => 7, 'city_name' => '중구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 7, 'city_name' => '남구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 7, 'city_name' => '동구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 7, 'city_name' => '북구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 7, 'city_name' => '울주군', 'created_at' => now(), 'updated_at' => now(),],
            //세종특별자치시
            ['state_id' => 8, 'city_name' => '세종특별자치시', 'created_at' => now(), 'updated_at' => now(),],
            //경기도
            ['state_id' => 9, 'city_name' => '수원시 장안구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '수원시 권선구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '수원시 팔달구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '수원시 영통구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '성남시 수정구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '성남시 중원구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '성남시 분당구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '의정부시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '안양시 만안구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '안양시 동안구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '부천시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '광명시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '평택시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '동두천시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '안산시 상록구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '안산시 단원구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '고양시 덕양구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '고양시 일산동구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '고양시 일산서구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '과천시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '구리시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '남양주시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '오산시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '시흥시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '군포시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '의왕시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '하남시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '용인시 처인구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '용인시 기흥구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '용인시 수지구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '파주시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '이천시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '안성시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '김포시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '화성시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '광주시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '양주시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '포천시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '여주시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '연천군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '가평군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 9, 'city_name' => '양평군', 'created_at' => now(), 'updated_at' => now(),],
            //강원도
            ['state_id' => 10, 'city_name' => '춘천시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 10, 'city_name' => '원주시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 10, 'city_name' => '강릉시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 10, 'city_name' => '동해시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 10, 'city_name' => '태백시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 10, 'city_name' => '속초시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 10, 'city_name' => '삼척시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 10, 'city_name' => '홍천군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 10, 'city_name' => '횡성군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 10, 'city_name' => '영월군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 10, 'city_name' => '평창군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 10, 'city_name' => '정선군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 10, 'city_name' => '철원군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 10, 'city_name' => '화천군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 10, 'city_name' => '양구군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 10, 'city_name' => '인제군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 10, 'city_name' => '고성군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 10, 'city_name' => '양양군', 'created_at' => now(), 'updated_at' => now(),],
            //충청북도
            ['state_id' => 11, 'city_name' => '청주시 상당구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 11, 'city_name' => '청주시 서원구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 11, 'city_name' => '청주시 흥덕구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 11, 'city_name' => '청주시 청원구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 11, 'city_name' => '충주시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 11, 'city_name' => '제천시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 11, 'city_name' => '보은군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 11, 'city_name' => '옥천군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 11, 'city_name' => '용동군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 11, 'city_name' => '증평군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 11, 'city_name' => '진천군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 11, 'city_name' => '괴산군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 11, 'city_name' => '음성군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 11, 'city_name' => '단양군', 'created_at' => now(), 'updated_at' => now(),],
            //충청남도
            ['state_id' => 12, 'city_name' => '천안시 동남구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 12, 'city_name' => '천안시 서북구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 12, 'city_name' => '공주시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 12, 'city_name' => '보령시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 12, 'city_name' => '아산시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 12, 'city_name' => '서산시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 12, 'city_name' => '논산시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 12, 'city_name' => '계룡시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 12, 'city_name' => '당진시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 12, 'city_name' => '금산군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 12, 'city_name' => '부여군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 12, 'city_name' => '서천군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 12, 'city_name' => '청양군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 12, 'city_name' => '홍성군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 12, 'city_name' => '예산군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 12, 'city_name' => '태안군', 'created_at' => now(), 'updated_at' => now(),],
            //전라북도
            ['state_id' => 13, 'city_name' => '전주시 완산구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 13, 'city_name' => '전주시 덕진구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 13, 'city_name' => '군산시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 13, 'city_name' => '익산시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 13, 'city_name' => '정읍시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 13, 'city_name' => '남원시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 13, 'city_name' => '김제시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 13, 'city_name' => '완주군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 13, 'city_name' => '진안군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 13, 'city_name' => '무주군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 13, 'city_name' => '장수군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 13, 'city_name' => '임실군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 13, 'city_name' => '순창군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 13, 'city_name' => '고창군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 13, 'city_name' => '부안군', 'created_at' => now(), 'updated_at' => now(),],
            //전라남도
            ['state_id' => 14, 'city_name' => '목포시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 14, 'city_name' => '여수시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 14, 'city_name' => '순천시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 14, 'city_name' => '나주시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 14, 'city_name' => '광양시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 14, 'city_name' => '담양군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 14, 'city_name' => '곡성군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 14, 'city_name' => '구례군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 14, 'city_name' => '고흥군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 14, 'city_name' => '보성군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 14, 'city_name' => '화순군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 14, 'city_name' => '장흥군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 14, 'city_name' => '강진군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 14, 'city_name' => '해남군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 14, 'city_name' => '영암군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 14, 'city_name' => '무안군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 14, 'city_name' => '함평군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 14, 'city_name' => '영광군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 14, 'city_name' => '장성군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 14, 'city_name' => '완도군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 14, 'city_name' => '진도군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 14, 'city_name' => '신안군', 'created_at' => now(), 'updated_at' => now(),],
            //경상북도
            ['state_id' => 15, 'city_name' => '포항시 남구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 15, 'city_name' => '포항시 북구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 15, 'city_name' => '경주시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 15, 'city_name' => '김천시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 15, 'city_name' => '안동시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 15, 'city_name' => '구미시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 15, 'city_name' => '영주시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 15, 'city_name' => '영천시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 15, 'city_name' => '상주시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 15, 'city_name' => '문경시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 15, 'city_name' => '경산시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 15, 'city_name' => '군위군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 15, 'city_name' => '의성군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 15, 'city_name' => '청송군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 15, 'city_name' => '영양군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 15, 'city_name' => '영덕군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 15, 'city_name' => '청도군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 15, 'city_name' => '고령군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 15, 'city_name' => '성주군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 15, 'city_name' => '칠곡군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 15, 'city_name' => '예천군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 15, 'city_name' => '봉화군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 15, 'city_name' => '울진군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 15, 'city_name' => '울릉군', 'created_at' => now(), 'updated_at' => now(),],
            //경상남도
            ['state_id' => 16, 'city_name' => '창원시 의창구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 16, 'city_name' => '창원시 성산구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 16, 'city_name' => '창원시 마산합포구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 16, 'city_name' => '창원시 마산회원구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 16, 'city_name' => '진해구', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 16, 'city_name' => '진주시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 16, 'city_name' => '통영시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 16, 'city_name' => '사천시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 16, 'city_name' => '김해시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 16, 'city_name' => '밀양시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 16, 'city_name' => '거제시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 16, 'city_name' => '양산시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 16, 'city_name' => '의령군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 16, 'city_name' => '함안군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 16, 'city_name' => '창녕군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 16, 'city_name' => '고성군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 16, 'city_name' => '남해군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 16, 'city_name' => '하동군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 16, 'city_name' => '산청군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 16, 'city_name' => '함양군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 16, 'city_name' => '거창군', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 16, 'city_name' => '합천군', 'created_at' => now(), 'updated_at' => now(),],
            //제주특별자치도
            ['state_id' => 17, 'city_name' => '제주시', 'created_at' => now(), 'updated_at' => now(),],
            ['state_id' => 17, 'city_name' => '서귀포시', 'created_at' => now(), 'updated_at' => now(),],
        ]);
    }
}